1 --한 줄 주석
2 /*범위주석*/

/*SQL 1개 실행: CTRL+ENTER
 * SQL 여러개 실행 : (블럭 후)ALT+X
 * 
 * */

ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

--계정생성
CREATE USER KH_PEJ IDENTIFIED BY KH1234;

--생성된 계정에 접속+자원관리 권한 추가
GRANT CONNECT, RESOURCE TO KH_PEJ;

--객체 생성 공간 할당
ALTER USER KH_PEJ
DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;



ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

--계정생성
CREATE USER WORKBOOK IDENTIFIED BY KH1234;

--생성된 계정에 접속+자원관리 권한 추가
GRANT CONNECT, RESOURCE TO WORKBOOK;

--객체 생성 공간 할당
ALTER USER WORKBOOK
DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;





